Sprint 3/step 1
cactys/react-burger pull request #15
Opened 2023-03-05 10:30 UTC by cactys

2023-03-10 03:13 UTC, ArslanDev666 requested changes
## Code Review

Здравствуйте!

Отличная работа.

### **Вы молодец!**

- Сборка и запуск проекта выполняются без ошибок;
- Теперь у вас есть роутинг;
- Есть регистрация и авторизация;

### **Но есть несколько замечаний, которые нужно исправить:**

- В файлах, где содержится `jsx`, нужно поменять расширение с `.js` на `.jsx`. Только не забудьте удалить `.js` файлы;

- Вы должны добавлять в хедер запроса `POST /orders`, токен пользователя `Bearer ...`, чтобы сервер понимал что заказ сделал зарегистрированный пользователь (время обработки заказа должно быть в разы больше, если вы всё правильно сделали);

- `/reset-password` должен быть доступен неавторизованным пользователям только после посещения маршрута /forgot-password и ввода адреса электронной почты для восстановления пароля.

- По чек-листу нужно: При клике по ингредиенту происходит переход на маршрут /ingredients/:id и открывается модальное окно с описанием ингредиента. При прямом переходе на этот маршрут открывается страница с информацией об ингредиенте.

- У вас не работает закрытие модального окна по нажатию `Esc`, нужно это исправить. Этот функционал должен быть в компоненте `modal`;ƒ

- <https://disk.yandex.com/i/E3CWD-DDYSYIqw> - кажется, тут шрифт слетел;

- Вы должны вешать обработчик на событие onSubmit элемента form, а не на кнопку;

#### **Хочу напомнить, что работа может быть принята, только после исправления всех "Надо исправить". Перед отправкой на ревью, проверьте работоспособность проекта и наличие возможных ошибок в консоли браузера (кнопка F12).**

2023-03-10 03:13 UTC, ArslanDev666 commented on src/components/ProfileForm/ProfileForm.js
> +          onClick={handleSubmit}
**Надо исправить:**

Вы должны вешать обработчик на событие `onSubmit` элемента `form`, а не на кнопку.

2023-03-10 03:13 UTC, ArslanDev666 commented on src/pages/ForgotPassword/ForgotPassword.js
> +      <form className={forgotPasswordStyle.form} onSubmit={(e) => onSubmit(e)}>
**Можно лучше:**

Лучше вынести обработчик событий в отдельную функцию.

2023-03-10 03:13 UTC, ArslanDev666 commented on src/pages/ResetPassword/ResetPassword.js
> +      onSubmit={(e) => onSubmit(e)}
**Надо исправить:**

Вы должны вешать обработчик на событие `onSubmit` элемента `form`, а не на другой элемент.

2023-03-10 03:13 UTC, ArslanDev666 commented on src/services/action/User.js
> +          console.log(err.message);
**Надо исправить:**

здесь и далее.

В приложении не должно быть консоль логов или дебаггеров. Вместо console.log используйте console.error() для ошибок.

2023-03-10 03:13 UTC, ArslanDev666 commented on src/services/action/User.js
> +            case 'jwt expired': {
**Можно лучше:**

Лучше сделать отдельный запрос, который будет проверять истёк ли токен, или нет.
Обрабатывать ошибки запросов и при возникновении ошибки jwt expired и вызывать обновление токена при ошибке

Для этого используйте обертку над fetch, примерно такую

```js
// например вот так
export const fetchWithRefresh = async (url, options) => {
  try {
    const res = await fetch(url, options);
    return await checkResponse(res);
  } catch (err) {
    if (err.message === 'jwt expired') {
      const refreshData = await refreshToken();
      if (!refreshData.success) {
        Promise.reject(refreshData);
      }
      localStorage.setItem('refreshToken', refreshData.refreshToken);
      setCookie('accessToken', refreshData.accessToken);
      options.headers.authorization = refreshData.accessToken;
      const res = await fetch(url, options);
      return await checkResponse(res);
    } else {
      return Promise.reject(err);
    }
  }
};
```

2023-03-10 03:13 UTC, ArslanDev666 commented on src/services/action/User.js
> +          case 'email or password are incorrect': {
**Можно лучше:**

Лучше создать объект с ошибками, и использовать его.
Т.е. нужно все виды ошибок вынести в константу в виде объекта;

2023-03-10 03:13 UTC, ArslanDev666 commented on src/components/OrderDetails/OrderDetails.js
>    }, [dispatch, bun, ingredients]);
**Надо исправить:**

запрос лучше делать в `burger-constructor`, в обработчике `handleOrderButtonClick`. Иначе сейчас у вас просходит 2 запроса, вместо 1.

2023-03-10 19:39 UTC, cactys commented on src/services/action/User.js
> +            case 'jwt expired': {
Не уверен, правильно ли я сделал.

2023-03-10 21:24 UTC, cactys commented on src/services/action/User.jsx
> +              console.log('jwt');
Удалить

2023-03-11 06:09 UTC, ArslanDev666 approved these changes
## Code Review

Здравствуйте!

Отличная работа.

### **Вы молодец! Работа принята, удачи в дальнейшем обучении!**

- Все замечания были исправлены;

### **Рекомендую исправить:**

- У редьюсеров и экшенов, не нужно было менять расширение, у них будет просто `.js`, т.к. там не содержится `jsx`.

- Отметил в коде, где вам ещё нужно добавить проверку на токен.

2023-03-11 06:09 UTC, ArslanDev666 commented on src/services/action/User.jsx
> +export function updateUserInfo(body) {
**Надо исправить:**

Тут вы тоже должны проверять, не истёк ли токен.

2023-03-11 06:09 UTC, ArslanDev666 commented on src/services/action/OrderDetails.jsx
> +export function orderDetail(ingredientId) {
**Надо исправить:**

Тут вы тоже должны проверять, не истёк ли токен.

2023-03-11 06:13 UTC, ArslanDev666 commented on src/services/action/User.js
> +            case 'jwt expired': {
не совсем, но это не критично. 

Я имел ввиду, что это просто такой же запрос как и другие, просто внутри есть кое-какая логика. 
Вот так использовать, также как и обычный `fetch` - https://disk.yandex.com/i/W3HdY4Ha7P6qfA;

Только вам, скорее всего, нужно будет его чуточку адаптировать под себя)

2023-03-16 09:55 UTC, merged