sprint-1/step-2
cactys/react-burger pull request #4
Opened 2023-02-11 18:45 UTC by cactys

2023-02-12 20:34 UTC, andryxxa93 requested changes
Очень хорошая работа! 
Что понравилось:
- Есть проверка успешности запроса
- Нет лишнего кода
- Есть отписка от слушателя событий.

Однако есть пару моментов, которые необходимо исправить, чтобы работа была принята.

Необходимо исправить:
- Проект не собирается из-за ошибок. 
Первая связанна с наличием в проекте конфига для typescript `tsconfig.json` - который сейчас не нужен, его необходимо удалить.
<img width="1347" alt="Снимок экрана 2023-02-12 в 23 18 49" src="https://user-images.githubusercontent.com/60173362/218334957-6624da81-97f3-4031-9007-6146c1c9ddcc.png">

Вторая связана с отсутствием некоторых компонентов.
<img width="1438" alt="Снимок экрана 2023-02-12 в 23 20 26" src="https://user-images.githubusercontent.com/60173362/218335031-66abf07f-5a89-4eb8-ad44-fa8c21543408.png">

- В консоли есть ошибки связанные с `propTypes`
<img width="1440" alt="Снимок экрана 2023-02-12 в 23 22 43" src="https://user-images.githubusercontent.com/60173362/218335133-9c53fdd2-0eb4-46ae-bafd-ca5fa77aa747.png">

- Есть ошибка с настройками `pretier` 
<img width="1440" alt="Снимок экрана 2023-02-12 в 23 24 05" src="https://user-images.githubusercontent.com/60173362/218335211-e000dcf9-47a1-4706-a3f7-705f97a24843.png">

- Необходимо вынести из компонента `App` логику и вызовы модальных окон
- Дописать содержимое некоторых пропсов в propTypes
- Убрать у `ModalOverlay` `children`

Более подробно описание проблемы смотрите комментарии в pull request.

В pull request вы так же найдете комментарии с рекомендациями как **можно улучшить** код. Их делать не обязательно, однако в будущем они могут помочь избежать ошибок и сделать код лучше.

Удачных правок!

2023-02-12 20:34 UTC, andryxxa93 commented on src/components/App/App.js
> +    }
**Необходимо исправить**
Данная функция должна находиться внутри компонента `Modal`. Компонент `App` это композиционный компонент - в нем должно быть минимальное количество настроек и функций.

2023-02-12 20:34 UTC, andryxxa93 commented on src/components/App/App.js
> +      </Modal>
**Необходимо исправить**
Вызов модальных окон необходимо перенести в компоненты  к которым они относятся. Т.е. в конструктор и список ингредиентов. Компоненту `App` не нужно управлять модальными окнами.

2023-02-12 20:34 UTC, andryxxa93 commented on src/components/IngredientDetails/IngredientDetails.js
> +  ingredientDetails: PropTypes.object.isRequired,
**Необходимо исправить**
Сейчас получается, что под `ingredientDetails` может прийти объект любого содержания. Необходимо конкретно указать содержимое этого объекта

2023-02-12 20:34 UTC, andryxxa93 commented on src/components/ModalOverlay/ModalOverlay.js
> +const ModalOverlay = ({ children, isOpen, onClose }) => {
**Надо исправить**

у ModalOverlay не должно быть children, это просто компонент подложки а не контейнер

2023-02-13 08:25 UTC, cactys commented on src/components/IngredientDetails/IngredientDetails.js
> +  ingredientDetails: PropTypes.object.isRequired,
Я так и не понял как вообще это работает =). А есть может информация, как дебажить такое?

2023-02-13 15:42 UTC, andryxxa93 commented on src/components/IngredientDetails/IngredientDetails.js
> +  ingredientDetails: PropTypes.object.isRequired,
Не до конца понял ваш вопрос. Как `propTypes` помогает в разработке? Вы описали `propTypes` компонента, если какой-то пропс не будет передан или не под тем типом, то в консоли разработчика появится ошибка, но она не будет вызывать краш приложения.

2023-02-13 15:44 UTC, andryxxa93 approved these changes
Супер! Все замечания исправлены, вы отлично поработали, работа принята.
Желаю удачного продолжения обучения!

2023-02-13 15:44 UTC, andryxxa93 commented on src/components/ModalOverlay/ModalOverlay.js
> +      // className={`${modalOverlayStyle.overlay} ${
**Можно улучшить**
Ненужный код лучше удалять

2023-02-13 15:59 UTC, merged