sprint-2/step-2
cactys/react-burger pull request #6
Opened 2023-02-17 06:25 UTC by cactys

2023-02-25 23:01 UTC, randomroot requested changes
**Доброго времени суток!** ☀️ 🌙 

Вы проделали отличную работу по добавлению DnD и Redux в ваш проект, хорошо построили архитектуру вашего проекта с разделением на представление и хранилище, реализовано нажатие на переключатель в навигации по ингредиентам, новый код лаконичен, в редьюсерах нет ничего лишнего, происходит сброс состояния после завершения операций или сбоях при выполнении, **так держать** 👍 

Тем не менее, для успешной сдачи работы вам необходимо внимательно ознакомиться с комментариями, оставленными в рамках ревью и провести необходимые **изменения**, обратив особое внимание на следующие моменты:

- Нижняя булка повернута некорректно (см. https://disk.yandex.ru/i/kP1BJe042oQzaw);
- В заказе следует расположить два идентификатора булки - один в начале массива, другой в конце, также как они располагаются в конструкторе;
- Обратите внимание на корректное использование функций `map` и `filter` в рамках вашего проекта;
- Не следует использовать для булки в сторе массив, т.к. она может быть только одного вида, либо отсутствовать, это может добавить лишних операций при взаимодействии с ней;

Также, в рамках ревью были предложены **улучшения** вашего кода, которое могут повысить его качество, исправить возможные проблемы в будущем и углубить ваше значение по курсу.

---

Перед повторной сдачей, пожалуйста, убедитесь в том, что проект работает **корректно** и **полностью**, согласно условиям задания и чек-листу, а в консоли браузера и в консоли вашей IDE **нет ошибок** и присутствует **минимально** возможное кол-во **предупреждений**. Работа будет принята **только** после исправления всех комментариев с меткой "Надо исправить". 

---

**Успешного вам рефакторинга, хорошего настроения и отличного дня!** 🐈

2023-02-26 07:57 UTC, cactys commented on src/components/OrderDetails/OrderDetails.js
> +    ingredients.map((ingredient) => ingredientId.push(ingredient._id));
Исправил на ```forEach```, а можно использовать ```map``` но вот так?
```js
const ingredientId = [
    ...bun.map((item) =>item._id),
    ...ingredients.map((ingredient) => ingredient._id),
    ...bun.map((item) => item._id),
];
```

2023-02-26 10:06 UTC, randomroot commented on src/components/OrderDetails/OrderDetails.js
> +    ingredients.map((ingredient) => ingredientId.push(ingredient._id));
Да, так правильно, в приоритете всегда лучше держать `const` переменные, чем `let`.

2023-02-26 14:04 UTC, randomroot approved these changes
🟢 **Работа принята:**

Все необходимые правки были внесены, код улучшен согласно рекомендациям, критических замечаний больше не имеется, **так держать**👍

Отличная работа, **желаю вам хорошего дня и успехов в дальнейшем обучении**! 🐈

2023-02-26 18:13 UTC, merged